### PR TITLE
fix can't back images when touch cancel button &  Cancel button cause the function holding infinitely

### PR DESCRIPTION
**Pull request by HenryGaoGH**
#20 Cancel button cause the function holding infinitely is fixed

fix can't back images when touch cancel button.

### CODE REVIEW

**Comment by howljs** [comment]
@HenryGaoGH 
Thank you for your PR. I think you will need throw error, because if you return empty array, you will not be able to know if you are unchecking the previous images or canceling the picker.

```
mediaPickerResult?.error("CANCELED", "User has canceled the picker", null)
```

Similar to the iOS handling:
https://github.com/howljs/hl_image_picker/blob/464dc1e70e757b8f2e2ccb7efd1c14d4dc0d877f/hl_image_picker_ios/ios/Classes/HLImagePickerPlugin.swift#L331

**Comment by howljs** [comment]
I will check again and help you in fixing this issue right now

**Comment by HenryGaoGH** [comment]
> @HenryGaoGH Thank you for your PR. I think you will need throw error, because if you return empty array, you will not be able to know if you are unchecking the previous images or canceling the picker.
> 
> ```
> mediaPickerResult?.error("CANCELED", "User has canceled the picker", null)
> ```
> 
> Similar to the iOS handling:
> 
> https://github.com/howljs/hl_image_picker/blob/464dc1e70e757b8f2e2ccb7efd1c14d4dc0d877f/hl_image_picker_ios/ios/Classes/HLImagePickerPlugin.swift#L331

You are right!
Returning an exception is better than successfully returning an empty array

**Comment by howljs** [comment]
Screenshot 2024-04-24 at 10 46 17

@HenryGaoGH I checked and it's working fine. Please help me update PR and test it again. Thanks

**Comment by HenryGaoGH** [comment]
> Screenshot 2024-04-24 at 10 46 17
> @HenryGaoGH I checked and it's working fine. Please help me update PR and test it again. Thanks

yeap!  I have also dealt with it

**Comment by howljs** [comment]
sorry. I forgot, we also need to update openCamera and openCropper too

**Comment by HenryGaoGH** [comment]
> sorry. I forgot, we also need to update openCamera too. Don't need update openCropper. Let me know when you updated the PR, I will merge it. Thanks
> 
> 
> 
> Screenshot 2024-04-24 at 11 01 31
> 
> 

OK, I'll deal with it after lunch. 😄

**Comment by HenryGaoGH** [comment]
@howljs Pls. check it and approved

**Comment by howljs** [comment]
The new version is available 🎉 

Screenshot 2024-04-24 at 12 14 58

**Pull request merged**
